FROM httpd:2.4

# Copie ton fichier de config Apache
COPY ./httpd.conf /usr/local/apache2/conf/httpd.conf

# Copie une page d’accueil simple (TP "landing page")
COPY ./index.html /usr/local/apache2/htdocs/index.html

