- name: Launch database container
  community.docker.docker_container:
    name: database
    image: juniteko/tp-devops-database:latest
    state: started
    restart_policy: unless-stopped

    env:
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ db_password }}"
      POSTGRES_DB: "{{ db_name }}"
    networks:
      - name: app-network
