name: CI devops 2025

on:
  push:
    branches:
      - maing
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      # Étape 1 - Récupérer le code du repo
      - uses: actions/checkout@v4

      # Étape 2 - Installer Java (JDK 21)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Étape 3 - Builder et tester le projet Maven
      - name: Build and test with Maven
        run: mvn clean verify --file ./backend/simple-api/pom.xml
#