services:
  database:
    image: juniteko/tp-devops-database
    container_name: postgres-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    image: juniteko/tp-devops-simple-api
    container_name: backend
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: db
      DB_USER: usr
      DB_PASSWORD: pwd
    networks:
      - app-network
    ports:
      - "8080:8080"

  httpd:
    image: juniteko/tp-devops-httpd
    container_name: http-server
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
