name: CD - Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04

    steps:
      # Étape 1 - Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 - Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Étape 3 - Construire et pousser l'image Docker du backend
      - name: Build and Push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./docker_tp/backend
          file: ./docker_tp/backend/docker_tp/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
