name: CD - Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Connexion à Docker Hub (comme indiqué dans le TP)
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Étape 3 : Build + Push de l’image backend
      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./docker_tp/backend
          file: ./docker_tp/backend/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # Étape 4 : Build + Push de l’image database
      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./docker_tp/database
          file: ./docker_tp/database/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # Étape 5 : Build + Push de l’image httpd
      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./docker_tp/httpd
          file: ./docker_tp/httpd/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}
