- name: Launch API container
  community.docker.docker_container:
    name: backend
    image: juniteko/tp-devops-simple-api:latest
    state: started
    restart_policy: on-failure

    env:
      SPRING_DATASOURCE_URL: "{{ spring_datasource_url }}"
      SPRING_DATASOURCE_USERNAME: "{{ spring_datasource_username }}"
      SPRING_DATASOURCE_PASSWORD: "{{ spring_datasource_password }}"
    networks:
      - name: app-network
      - name: proxy-network
