- name: Launch API container
  community.docker.docker_container:
    name: backend
    image: juniteko/tp-devops-simple-api:latest
    pull: yes
    state: started
    recreate: yes
    restart_policy: always
    networks:
      - name: app-network
    env:
      SPRING_DATASOURCE_URL: "{{ spring_datasource_url }}"
      SPRING_DATASOURCE_USERNAME: "{{ spring_datasource_username }}"
      SPRING_DATASOURCE_PASSWORD: "{{ spring_datasource_password }}"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
